name: Generate SDK

on:
  repository_dispatch:
    types: [generate-sdk]

env:
  PACKAGE_NAME: freee/freee-accounting-sdk
  SCHEMA_URL_TEMP: https://gist.githubusercontent.com/shibayan/3fdf5a66554e5e7ccfe4cc8350db86d7/raw/64548c7ad8bb4c65c0bbe1748ca8f759da648aa6/api-schema.yml
  KEEP_CURRENT_HEADER_SELECTOR: true
  
jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Check client_payload
      if: ${{ ! (github.event.client_payload.origin_ref && contains(github.event.client_payload.origin_ref, 'refs/tags/')) }}
      run: |
        echo $EVENT
        echo '::error::Invalid request'
        exit 1
      env:
        EVENT: ${{ toJson(github.event) }}

    - uses: actions/github-script@v2
      id: release_tag
      with:
        result-encoding: string
        script: |
          const { origin_ref } = context.payload.client_payload
          const words = origin_ref.split('/')
          return words[2]

    - name: Install packages
      run: |
        sudo snap install yq

    - uses: actions/checkout@v2    

    - name: Remove old codes
      run: |
        rm -rf sdk/src sdk/docs sdk/target sdk/pom.xml

    - name: Update lib version
      run: |
        yq write -i .openapi-generator/config.yml artifactVersion ${{ steps.release_tag.outputs.result }}

    - name: Generate APIs
      env:
        SCHEMA_URL: https://raw.githubusercontent.com/freee/freee-api-schema/${{ steps.release_tag.outputs.result }}/v2020_06_15/open-api-3/api-schema.yml
      run: |
        docker run --rm -u "$(id -u $USER):$(id -g $USER)" -v "${PWD}:/local" openapitools/openapi-generator-cli:latest-release generate \
          -i ${{ env.SCHEMA_URL_TEMP }} \
          -c /local/.openapi-generator/config.yml \
          -g java \
          -o /local/sdk
        cd sdk && rm -rf .gradle/ .openapi-generator .openapi-generator-ignore .travis.yml  build.gradle  build.sbt  git_push.sh gradle.properties gradle gradlew gradlew.bat settings.gradle README.md api/openapi.yaml

    - name: Update sdk/pom.xml
      shell: pwsh
      run: |
        ./update-pom-xml.ps1

    - name: Git
      run: |
        git stash push .openapi-generator/config.yml
        git fetch
        git checkout master
        git config --local user.name "API Generator"
        git stash pop
        git add .
        git commit -m "Generated by release ${{ steps.release_tag.outputs.result }}"
        git reset --hard HEAD
        git clean -fdx

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
