name: Release artifacts

on:
  release:
    types:
      - published
      - prereleased
      - released
      - created  # temporary for dev
      - edited   # temporary for dev

jobs:
  get_release_tag:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.release_tag.outputs.result }}

    steps:
    - name: Show github.ref
      run: echo "${{ toJson(github.ref) }}"

    - name: Check client_payload
      if: ${{ ! (github.ref && contains(github.ref, 'refs/tags/')) }}
      run: |
        echo '::error::This workflow\'s ref does not include release tag'
        exit 1

    - uses: actions/github-script@v2
      id: test
      with:
        result-encoding: string
        script: |
          return context.payload

    - name: test
      run: echo "$PAYLOAD"
      env:
        PAYLOAD: ${{ steps.test.outputs.result }}

    - uses: actions/github-script@v2
      id: release_tag
      with:
        result-encoding: string
        script: |
          const words = context.payload.ref.split('/')
          return words[2]

  build:
    runs-on: ubuntu-latest
    needs: get_release_tag

    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        java-package: jdk
        architecture: x64

    - name: Package
      run: |
        mvn clean package --no-transfer-progress -DperformRelease=true

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        java-package: jdk
        architecture: x64
        server-id: dev
        server-username: MAVEN_USERNAME
        server-password: MAVEN_USER_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Deploy
      run: |
        mvn clean deploy --no-transfer-progress -DperformRelease=true -DskipTests=true -Dchangelist= -Drevision=${{ needs.get_release_tag.outputs.release_tag }}
