name: Release artifacts

on:
  release:
    types:
      - published
      - prereleased
      - released

env:
  JAVA_VERSION: '1.8'
  JAVA_PACKAGE: jdk
  JAVA_ARCHITECTURE: x64
  WORKING_DIR: ./sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
        java-package: ${{ env.JAVA_PACKAGE }}
        architecture: ${{ env.JAVA_ARCHITECTURE }}

    - name: Package
      run: |
        mvn clean package --no-transfer-progress
      working-directory: ${{ env.WORKING_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
        java-package: ${{ env.JAVA_PACKAGE }}
        architecture: ${{ env.JAVA_ARCHITECTURE }}
        server-id: dev
        server-username: MAVEN_USERNAME
        server-password: MAVEN_USER_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Deploy
      run: |
        mvn clean deploy --no-transfer-progress -DperformRelease=true -DskipTests=true -Dchangelist= -Drevision=${{ github.event.release.tag_name }}
      working-directory: ${{ env.WORKING_DIR }}
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_USER_PASSWORD: ${{ secrets.MAVEN_USER_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}