name: Test

on:
  push:

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    - name: Manage pom.xml
      uses: microsoft/variable-substitution@v1
      with:
        files: test.xml
      env:
        conntype: new_connType
        MyDB: TestDB
        webpages:Version: 1.1.7.3
        xdt:Transform: DelAttributes
        xdt:Locator: Match(tag)
        DefaultConnection: Url=https://primary;Database=db1;ApiKey=11111111-1111-1111-1111-111111111111;Failover = {Url:'https://secondary', ApiKey:'11111111-1111-1111-1111-111111111111'}
        OtherDefaultConnection: connectionStringValue2
        ParameterConnection: New_Connection_String From xml var subs
        connectionString: replaced_value
        invariantName: System.Data.SqlServer
        blatvar: ApplicationSettingReplacedValue
        log_level: error,warning
        Email:ToOverride: ''
        body: Hooray!
        nested.body: Fine!

    - name: Show
      run: |
        git diff

    - uses: actions/upload-artifact@v2
      with:
          name: updatedXmlFile
          path: test.xml
